package nu.staldal.mypass.ui.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import nu.staldal.mypass.ui.components.SecretField
import nu.staldal.mypass.vault.PasswordEntry
import nu.staldal.mypass.vault.Secret

/**
 * Add or edit one entry.
 *
 * The password is generated by default, as on the desktop; typing one is the
 * opt-in. Editing starts with the existing password kept, so changing only a
 * username or url never rotates the secret by accident.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EntryFormScreen(
    existing: PasswordEntry?,
    defaultLength: Int,
    defaultCharset: String,
    onBack: () -> Unit,
    onSave: (PasswordEntry) -> Unit,
    onGenerate: (Int, String) -> Secret?,
) {
    val editing = existing != null
    // Editable metadata retains its stored value; loaded entries have passed validation.
    var name by remember { mutableStateOf(existing?.name.orEmpty()) }
    var username by remember { mutableStateOf(existing?.username.orEmpty()) }
    var url by remember { mutableStateOf(existing?.url.orEmpty()) }
    var realm by remember { mutableStateOf(existing?.realm.orEmpty()) }
    var keepPassword by remember { mutableStateOf(editing) }
    var password by remember {
        mutableStateOf(
            if (editing) "" else onGenerate(defaultLength, defaultCharset)?.expose().orEmpty()
        )
    }
    var length by remember { mutableStateOf(defaultLength.toString()) }
    var charset by remember { mutableStateOf(defaultCharset) }
    var showGeneratorOptions by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (editing) "Edit entry" else "Add entry") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
            )
        },
    ) { padding ->
        Column(
            Modifier
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            OutlinedTextField(
                value = name,
                onValueChange = { name = it },
                label = { Text("Name") },
                supportingText = { Text("What you call this entry. Never matched against a site.") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(12.dp))
            OutlinedTextField(
                value = username,
                onValueChange = { username = it },
                label = { Text("Username (optional)") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(12.dp))
            OutlinedTextField(
                value = url,
                onValueChange = { url = it },
                label = { Text("Site / url (optional)") },
                supportingText = {
                    Text(
                        "The one thing that lets a browser fill this entry. " +
                            "A hostname (github.com) or a full URL."
                    )
                },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(12.dp))
            OutlinedTextField(
                value = realm,
                onValueChange = { realm = it },
                label = { Text("HTTP realm (optional)") },
                supportingText = {
                    Text("For desktop MyPass's HTTP-authentication filling. Needs a url.")
                },
                enabled = url.isNotBlank(),
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )

            Spacer(Modifier.height(24.dp))
            Text("Password", style = MaterialTheme.typography.titleMedium)

            if (editing) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = keepPassword, onCheckedChange = { keepPassword = it })
                    Text("Keep the existing password")
                }
            }

            if (!keepPassword) {
                Spacer(Modifier.height(8.dp))
                SecretField(
                    value = password,
                    onValueChange = { password = it },
                    label = "Password",
                )
                Spacer(Modifier.height(8.dp))
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Button(
                        onClick = {
                            val requested = length.toIntOrNull() ?: defaultLength
                            onGenerate(requested, charset)?.let { password = it.expose() }
                        }
                    ) {
                        Text("Generate")
                    }
                    Spacer(Modifier.width(8.dp))
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(
                            checked = showGeneratorOptions,
                            onCheckedChange = { showGeneratorOptions = it },
                        )
                        Text("Options")
                    }
                }
                if (showGeneratorOptions) {
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = length,
                        onValueChange = { length = it.filter(Char::isDigit) },
                        label = { Text("Length") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                    )
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = charset,
                        onValueChange = { charset = it },
                        label = { Text("Characters to generate from") },
                        modifier = Modifier.fillMaxWidth(),
                    )
                }
            }

            Spacer(Modifier.height(24.dp))
            Button(
                onClick = {
                    onSave(
                        PasswordEntry(
                            name = name.trim(),
                            username = username.trim(),
                            password = if (keepPassword && existing != null) {
                                existing.password
                            } else {
                                Secret(password)
                            },
                            url = url.trim().ifEmpty { null },
                            realm = realm.trim().ifEmpty { null }
                                ?.takeIf { url.isNotBlank() },
                        )
                    )
                },
                enabled = name.isNotBlank() && (keepPassword || password.isNotEmpty()),
                modifier = Modifier.fillMaxWidth(),
            ) {
                Text(if (editing) "Save changes" else "Add entry")
            }
        }
    }
}
