package nu.staldal.pw.ui.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import nu.staldal.pw.vault.Secret

/** `pw generate`: a password that is not stored anywhere. */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun GenerateScreen(
    defaultLength: Int,
    defaultCharset: String,
    onBack: () -> Unit,
    onGenerate: (Int, String) -> Secret?,
    onCopy: (label: String, value: String, confirmation: String) -> Unit,
) {
    var length by remember { mutableStateOf(defaultLength.toString()) }
    var charset by remember { mutableStateOf(defaultCharset) }
    var generated by remember { mutableStateOf<String?>(null) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Generate password") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
            )
        },
    ) { padding ->
        Column(
            Modifier
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            OutlinedTextField(
                value = length,
                onValueChange = { length = it.filter(Char::isDigit) },
                label = { Text("Length") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(12.dp))
            OutlinedTextField(
                value = charset,
                onValueChange = { charset = it },
                label = { Text("Characters to generate from") },
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(16.dp))
            Button(
                onClick = {
                    generated = onGenerate(length.toIntOrNull() ?: defaultLength, charset)
                        ?.expose()
                },
                modifier = Modifier.fillMaxWidth(),
            ) {
                Text("Generate")
            }

            val password = generated
            if (password != null) {
                Spacer(Modifier.height(24.dp))
                Card(Modifier.fillMaxWidth()) {
                    Text(
                        password,
                        style = MaterialTheme.typography.bodyLarge
                            .copy(fontFamily = FontFamily.Monospace),
                        modifier = Modifier.padding(16.dp),
                    )
                }
                Spacer(Modifier.height(8.dp))
                Row {
                    OutlinedButton(
                        onClick = {
                            onCopy("pw password", password, "Password copied")
                        }
                    ) {
                        Text("Copy")
                    }
                }
                Spacer(Modifier.height(8.dp))
                Text(
                    "This password is not stored. Add an entry to keep it.",
                    style = MaterialTheme.typography.bodySmall,
                )
            }
        }
    }
}
